/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    FieldCheckbox: typeof import('./src/fields/core/fieldCheckbox.vue')['default']
    FieldChecklist: typeof import('./src/fields/core/fieldChecklist.vue')['default']
    FieldCleave: typeof import('./src/fields/optional/fieldCleave.vue')['default']
    FieldDateTimePicker: typeof import('./src/fields/optional/fieldDateTimePicker.vue')['default']
    FieldGoogleAddress: typeof import('./src/fields/optional/fieldGoogleAddress.vue')['default']
    FieldImage: typeof import('./src/fields/optional/fieldImage.vue')['default']
    FieldInput: typeof import('./src/fields/core/fieldInput.vue')['default']
    FieldLabel: typeof import('./src/fields/core/fieldLabel.vue')['default']
    FieldMasked: typeof import('./src/fields/optional/fieldMasked.vue')['default']
    FieldNoUiSlider: typeof import('./src/fields/optional/fieldNoUiSlider.vue')['default']
    FieldPikaday: typeof import('./src/fields/optional/fieldPikaday.vue')['default']
    FieldRadios: typeof import('./src/fields/core/fieldRadios.vue')['default']
    FieldRangeSlider: typeof import('./src/fields/optional/fieldRangeSlider.vue')['default']
    FieldSelect: typeof import('./src/fields/core/fieldSelect.vue')['default']
    FieldSelectEx: typeof import('./src/fields/optional/fieldSelectEx.vue')['default']
    FieldSpectrum: typeof import('./src/fields/optional/fieldSpectrum.vue')['default']
    FieldStaticMap: typeof import('./src/fields/optional/fieldStaticMap.vue')['default']
    FieldSubmit: typeof import('./src/fields/core/fieldSubmit.vue')['default']
    FieldSwitch: typeof import('./src/fields/optional/fieldSwitch.vue')['default']
    FieldTextArea: typeof import('./src/fields/core/fieldTextArea.vue')['default']
    FieldUpload: typeof import('./src/fields/core/fieldUpload.vue')['default']
    FieldVueMultiSelect: typeof import('./src/fields/optional/fieldVueMultiSelect.vue')['default']
    FormGenerator: typeof import('./src/formGenerator.vue')['default']
    FormGroup: typeof import('./src/formGroup.vue')['default']
  }
}
